version: '3.8'
services:
  aaps-ci-preparation:
    container_name: aaps-ci-preparation
    image: lh0528/aaps-ci-preparation:latest
    ports:
      - "8082:8080"
    environment:
      - GOOGLE_SITE_VERIFICATION=${GOOGLE_SITE_VERIFICATION}
    restart: always
    networks:
        - aaps

  nginx:
      image: nginx:latest
      container_name: nginx-aaps-ci
      restart: always
      ports:
        - "81:80"
        - "8443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certs:/etc/nginx/certs
      networks:
        - aaps

networks:
  aaps:
    name: aaps-network
