name: Pre-release aaps-ci-auth.html

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  pre-release-auth-html:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create pre-release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-release-${{ steps.vars.outputs.sha_short }}
          name: Pre-release ${{ steps.vars.outputs.sha_short }}
          body: |
            Automated pre-release for aaps-ci-auth.html
          prerelease: true
          files: src/main/resources/static/aaps-ci-auth.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
