name: release aaps-ci-auth.html
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'pre-release?'
        required: true
        default: true
        type: boolean

jobs:
  release-auth-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Extract version from HTML
        id: version
        run: |
          VERSION=$(grep -oP '<div class="version-badge">v\K[0-9.]+(?=</div>)' src/main/resources/static/aaps-ci-auth.html)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create pre-release
        if: ${{ inputs.prerelease == true }}
        id: create_pre_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-release-${{ steps.version.outputs.version }}
          name: Pre-release ${{ steps.version.outputs.version }}
          body: |
            Automated pre-release for aaps-ci-auth.html
          prerelease: true
          files: src/main/resources/static/aaps-ci-auth.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        if: ${{ inputs.prerelease == false }}
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-v${{ steps.version.outputs.version }}
          name: release v${{ steps.version.outputs.version }}
          body: |
            Automated release for aaps-ci-auth.html
          prerelease: false
          files: src/main/resources/static/aaps-ci-auth.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
